### index

GET http://localhost:8080


### update
PATCH http://localhost:8080
Content-Type: application/json

{
  "name": "lawliet"
}

### url shortener
POST  http://localhost:9876
Content-Type: application/json

{
  "url": "http://www.google.com"
}


### url get
GET  http://localhost:9876/VU3aOb
